### ISSUE TITLE
How to use InlineTest?

### ISSUE THREAD

**Issue by cmcaine** [JuliaTesting/ReTest.jl#5]
> When using `@testset` "inline", i.e. within the source-code of a package, one can use the InlineTest package instead of ReTest, which only defines the strict minimum and also exports `@testset`, and therefore loads faster (even if ReTest itself loads fast, it can be desirable to have an even lighter dependency). But ReTest still has to be loaded (as a "test" dependency) in order to call retest.

How do I do this?

I've tried

```julia
using InlineTest

@testset "foo" begin
    @test 1 == 2
end

using ReTest

runtests()
```

and

```julia
module inner

using InlineTest

@testset "foo" begin
    @test 1 == 2
end

end

using ReTest

runtests()
```

And in both cases no tests are executed.

Replacing `InlineTest` with `ReTest` in either example works as expected.

**Comment by rfourquet** [comment]
Yeah, you are a victim of the immaturity of the package :)
I actually struggled trying to have tests passing on CI, without success, before registering `InlineTest`, and gave up temporarily, having the two packages in the same repo didn't make things easier on this front.

Anyway, assuming you used registered versions, the problem is that there is no registered version of `ReTest` which uses `InlineTest` yet. A solution is to checkout master for both, which is usable I think, or to use the `ReTest` version corresponding to `v0.1.0` of `InlineTest`, via `add ReTest#InlineTest-v0.1.0` in `Pkg` mode.

Thanks for trying this out!

**Comment by rfourquet** [comment]
A new version of `ReTest` (0.2.0) is now released which uses `InlineTest`. The examples of the OP are working by replacing `runtests()` with `retest()`, which is the new API, cf. the docs at https://juliatesting.github.io/ReTest.jl/dev/.
